default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: bordernone_dev

test:
  <<: *default
  database: bordernone_test
